### ISSUE TITLE
How to use with import?

### ISSUE THREAD

**Issue by junerockwell** [mister-ben/videojs-seek-buttons#7] opened 2017-09-01 05:14 UTC
## Description
I'm using Webpack 2 and VueJS 2. I'm able to `import` video.js. How can I `import` videojs-seek-buttons plugin?

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

````
import videojs from 'video.js';
import seekButtons from 'videojs-seek-buttons';
````

### Expected
I want to be able to follow the suggested syntax:
````
this.videoPlayer = videojs("my-video", {
  controls: true,
  nativeControlsForTouch: true,
  poster: 'https://cdn.selz.com/plyr/1.5/View_From_A_Blue_Moon_Trailer-HD.jpg?v1',
  plugins: {
     seekButtons: {
	 forward: 30,
	  back: 10
     }
  }
});
````

### Actual
The plugin is not added or `import`ed into the project. 

### Error output
![screen shot 2017-08-31 at 10 03 05 pm](https://user-images.githubusercontent.com/5051574/29956099-8a1576b0-8e99-11e7-8e8c-e8c4d5492c25.png)

## Additional Information
Please include any additional information necessary here. Including the following:

#### videojs
what version of videojs does this occur with?
video.js: 6.2.5
videojs-seek-buttons: 1.1.0

#### Additionally:
vue: 2.4.2
vue-router: 2.7.0
babel-core: 6.22.1
babel-loader: 7.1.1
webpack: 2.6.1

#### browsers
what browser are affected?
Chrome,
Firefox

#### OSes
what platforms (operating systems and devices) are affected?
MacOS 10.12.6 Sierra

### plugins
None.

**Comment by chriswang1990** [comment] 2017-09-20 07:22
I have encounter the same issue. I'm using react with webpack and use 'import' for all the modules.  when I tried with require('videojs-seek-buttons') or import 'videojs-seek-buttons', it show the errors that the plugin does not exist. Could you kindly help us with this issue? Thanks

**Comment by tp9106** [comment] 2017-12-12 07:12
I have the same issue with react and webpack. I found that it is caused by inconsistent video js version in my environment. I use video js 6, but the dependency defined in the package.json of this plugin is [video js 5](https://github.com/mister-ben/videojs-seek-buttons/blob/27831372854a7e125a5fabc129de5ee9151ec33a/package.json#L86). Even though in webpack I use ProvidePlugin to expose videojs as a global variable (videojs 6), when using import 'videojs-seek-buttons', the videojs variable seems to refer to another function (videojs 5 defined in package.json) when executing plugin code. I got it work by uninstall the videojs 5 dependency with in this plugin. I think this issue would be solved by modifying package.json to also support videojs 6, such as `"video.js": "^6.x.x || ^5.19.2"`

**Comment by mister-ben** [comment] 2017-12-28 19:44
Thanks @tp9106. This should be fixed with videojs-seek-buttons@beta

**Comment by wells** [comment] 2017-12-29 17:23
I was able to get version `1.1.0` of this plugin working with version `5.20.4` of video.js using webpack. 

I am having the same `seekButtons does not exist` issue with version `1.2.4` of this plugin on version `5.20.4` of video.js.

Personally, I'm having no end of trouble getting most plugins to work with version `6.x.x` of video.js, hence why I'm going to stay back on version `5.x.x` until later versions have stabilized.

What I'm using that works for the versions I'm on:

```
import videojs from 'video.js'
import 'videojs-seek-buttons'
```

**Comment by shanet** [comment] 2018-01-05 19:35
Thanks @wells. `1.2.0` and `5.20.4` is the only version combination that I've gotten to work. I'm unsure why.

**Comment by btimby** [comment] 2019-02-14 20:14
I am having this same problem. What I found is this...

When npm installs videojs-seek-buttons, it also pulls in another version of video.js (besides the one I already installed for my application).

Thus when I import videojs-seek-buttons, it registers itself with that over version of video.js. It is therefore not available to video.js which I have imported into my application.

If I manually remove the local copy, then all works as desired.

`rm -rf node_modules/videojs-seek-buttons/node_modules/video.js`

I wonder if the dependency is failing to match the version I have installed, which is: 7.4.1

https://github.com/mister-ben/videojs-seek-buttons/blob/master/package.json#L86

**Comment by mister-ben** [comment] 2019-02-24 19:45
I've updated the version of [videojs/generator-videojs-plugin](https://github.com/videojs/generator-videojs-plugin) this uses and in my tests it's working with Webpack. It's published as beta if anyone would like to check with their test cases.

`npm i videojs-seek-buttons@beta`

**Comment by forresthopkinsa** [comment] 2019-02-27 01:03
@mister-ben The beta solves the not-found problem (hooray! 🎉 ) but the buttons are invisible with it. Any ideas?

**Comment by mister-ben** [comment] 2019-02-27 03:55
That doesn't make sense... by updating the plugin template it's using postcss rather than scss now, but the output css is the same - the only difference is it groups some rules together:

Before:
```css
.video-js .vjs-seek-button.skip-back.skip-10::before {
  content: '\e059'
}
...
.video-js.vjs-v6 .vjs-seek-button.skip-back.skip-10 .vjs-icon-placeholder::before,
.video-js.vjs-v7 .vjs-seek-button.skip-back.skip-10 .vjs-icon-placeholder::before {
  content: '\e059'
}
```

Now
```css
.video-js .vjs-seek-button.skip-back.skip-10::before,
.video-js.vjs-v6 .vjs-seek-button.skip-back.skip-10 .vjs-icon-placeholder::before,
.video-js.vjs-v7 .vjs-seek-button.skip-back.skip-10 .vjs-icon-placeholder::before {
  content: '\e059'
}
```

I definitely see the icons. Do you have a test case to reproduce that?

**Comment by mister-ben** [comment] 2019-03-13 08:27
@forresthopkinsa are there steps to reproduce your issue with the icons?

**Comment by forresthopkinsa** [comment] 2019-03-17 03:54
Hey, sorry I didn't get back to you. I'll work on giving some repro steps this week.

**Comment by mister-ben** [comment] 2019-04-18 11:50
Closing as the original issue was resolved. 1.5.0 with that change is the release version on npm.

@forresthopkinsa if you can reproduce the issue and it's not just missing css as #15, please open a separate issue with the steps to reproduce.

**Closed by mister-ben** 2019-04-18 11:50 UTC
